/*SELECT
    CASE
        WHEN PAX_AGE BETWEEN 18 AND 30 THEN '18-30'
        WHEN PAX_AGE BETWEEN 31 AND 40 THEN '31-40'
		WHEN PAX_AGE BETWEEN 41 AND 50 THEN '41-50'
		WHEN PAX_AGE BETWEEN 51 AND 60 THEN '51-60'
        ELSE 'Above 60'
    END AS AgeGroup,
    COUNT(*) AS PassengerCount
FROM Passenger
GROUP BY
    CASE
        WHEN PAX_AGE BETWEEN 18 AND 30 THEN '18-30'
        WHEN PAX_AGE BETWEEN 31 AND 40 THEN '31-40'
		WHEN PAX_AGE BETWEEN 41 AND 50 THEN '41-50'
		WHEN PAX_AGE BETWEEN 51 AND 60 THEN '51-60'
        ELSE 'Above 60'
    END;*/

/*SELECT
    PAX_GENDER,
    AVG(PAX_AGE) AS Average_Age
FROM Passenger
GROUP BY PAX_GENDER;

SELECT
    PAX_GENDER,
    SUM(CASE WHEN LOYALTY_POINTS > 0 THEN 1 ELSE 0 END) AS PassengersWithLoyaltyPoints
FROM Passenger
GROUP BY PAX_GENDER;*/
--

/*SELECT 
DEPART_AIRPORT,
COUNT(*) AS FlightCount
FROM 
    Flight
WHERE 
    LEFT(DEPART_AIRPORT, 1) IN ('B', 'M', 'S')
GROUP BY 
    DEPART_AIRPORT;*/


/*SELECT COUNT(*) AS Number_Of_Flights
FROM Flight
WHERE FLIGHT_DATE BETWEEN '2021-12-15' AND '2021-12-31';

SELECT TOP 5
    ARRIVAL_AIRPORT
FROM Flight
GROUP BY ARRIVAL_AIRPORT
ORDER BY COUNT(*) DESC;*/


/*SELECT 
FLIGHT_NUM,
DEPART_AIRPORT,
ARRIVAL_AIRPORT,
DEPART_TIME,
ARRIVAL_TIME,
DATEDIFF(MINUTE, DEPART_TIME, ARRIVAL_TIME) AS Flight_Duration_in_Minutes
FROM Flight
WHERE DATEDIFF(MINUTE, DEPART_TIME, ARRIVAL_TIME) > 300;*/

--

/*SELECT COUNT(*) AS Passengers_with_Discount
FROM Price
WHERE DISCOUNT_AMT > 0;

SELECT
    Currency,
    CAST(AVG(TOTAL_AMT) AS DECIMAL(10,2)) AS AveragePrice
FROM Price
GROUP BY Currency;*/


/*SELECT
    CURRENCY,
    ROUND(MAX(TOTAL_AMT), 2) AS Highest_Price
FROM Price
GROUP BY CURRENCY;


SELECT
    CURRENCY,
    CAST(AVG(TAX_AMT) AS DECIMAL(10, 2)) AS Average_Tax_Amount
FROM Price
GROUP BY CURRENCY;*/

--

/*SELECT MANUFACTURER, COUNT(*) AS AircraftCount
FROM Aircraft
GROUP BY MANUFACTURER;

SELECT
    AIRCRAFT_TYPE,
    COUNT(*) AS AircraftCount
FROM Aircraft
GROUP BY AIRCRAFT_TYPE;*/

/*SELECT
AIRCRAFT_TYPE,
AVG(AIRCRAFT_CAPACITY) AS Average_Seating_Capacity
FROM Aircraft GROUP BY AIRCRAFT_TYPE;

SELECT
AIRCRAFT_TYPE,
MAX(AIRCRAFT_CAPACITY) AS Highest_Capacity
FROM Aircraft GROUP BY AIRCRAFT_TYPE;*/

--

/*SELECT
    Class_Name,
    SUM(CAST(SUBSTRING(SEAT_NUM, 1, LEN(SEAT_NUM) - 1) AS INT)) AS TotalSeats,
    SUM(CASE WHEN Available = 0 THEN CAST(SUBSTRING(SEAT_NUM, 1, LEN(SEAT_NUM) - 1) AS INT) ELSE 0 END) AS UnavailableSeats,
    SUM(CASE WHEN Available = 1 THEN CAST(SUBSTRING(SEAT_NUM, 1, LEN(SEAT_NUM) - 1) AS INT) ELSE 0 END) AS AvailableSeats
FROM CabinClass
GROUP BY Class_Name;*/
--
/*SELECT
CAST(SUM(CAST(PRIORITY_BOARDING AS INT)) * 100.0 / COUNT(*) AS DECIMAL(10, 2)) AS Percentage_Priority_boarding,
CAST(SUM(CAST(LOUNGE_ACCESS AS INT)) * 100.0 / COUNT(*) AS DECIMAL(10, 2)) AS Percentage_Lounge_access,
CAST(SUM(CAST(CHECKED_BAGGAGE AS INT)) * 100.0 / COUNT(*) AS DECIMAL(10, 2)) AS Percentage_Checked_Baggage,
CAST(SUM(CAST(MEAL_SERVICE AS INT)) * 100.0 / COUNT(*) AS DECIMAL(10, 2)) AS Percentage_Meal_Service,
CAST(SUM(CAST(InFLIGHT_MEDIA AS INT)) * 100.0 / COUNT(*) AS DECIMAL(10, 2)) AS Percentage_Inflight_media
FROM Services;*/
--

/*SELECT
    BOOKING_STATUS,
    COUNT(*) AS StatusCount
FROM Booking
GROUP BY BOOKING_STATUS;

SELECT TOP 5
F.FLIGHT_NUM, F.DEPART_AIRPORT, F.ARRIVAL_AIRPORT, P. TOTAL_AMT, P.CURRENCY
FROM Booking AS B
INNER JOIN Price AS P ON B.PRICE_ID = P.PRICE_ID
INNER JOIN Flight AS F ON B.FLIGHT_ID = F.FLIGHT_ID
WHERE P.CURRENCY IN ('USD') ORDER BY P.TOTAL_AMT DESC;*/


/*SELECT TOP 3
F.FLIGHT_NUM, F.DEPART_AIRPORT, F.ARRIVAL_AIRPORT, P. TOTAL_AMT, P.CURRENCY
FROM Booking AS B
INNER JOIN Price AS P ON B.PRICE_ID = P.PRICE_ID
INNER JOIN Flight AS F ON B.FLIGHT_ID = F.FLIGHT_ID
WHERE P.CURRENCY IN ('EUR') ORDER BY P.TOTAL_AMT DESC;

SELECT TOP 2
    A.AIRCRAFT_TYPE AS AircraftType,
    COUNT(B.Booking_ID) AS BookedSeats
FROM Aircraft AS A
LEFT JOIN Booking AS B ON A.Aircraft_ID = B.Aircraft_ID
GROUP BY A.AIRCRAFT_TYPE
ORDER BY BookedSeats DESC;*/

/*SELECT TOP 15
    P.PAX_Name, F.DEPART_AIRPORT, F.ARRIVAL_AIRPORT, CC.CLASS_NAME, Pr.CURRENCY, 
    SUM(Pr.TOTAL_AMT) AS Total_Spending
FROM BOOKING AS B
JOIN Passenger AS P ON P.PAX_ID = B.PAX_ID
JOIN Price AS Pr ON B.Price_ID = Pr.Price_ID
JOIN Flight AS F ON B.FLIGHT_ID = F.FLIGHT_ID
JOIN CabinClass AS CC ON B.CLASS_ID = CC.CLASS_ID
GROUP BY P.PAX_Name, F.DEPART_AIRPORT, F.ARRIVAL_AIRPORT,Pr.CURRENCY,CC.CLASS_NAME
ORDER BY Total_Spending DESC;*/

/*SELECT
    CC.CLASS_NAME,
    AVG(P.PAX_AGE) AS Average_Age
FROM BOOKING AS B
JOIN CabinClass AS CC ON B.Class_ID = CC.Class_ID
JOIN Passenger AS P ON B.PAX_ID = P.PAX_ID
GROUP BY CC.CLASS_NAME;

SELECT TOP 5
    F.DEPART_AIRPORT,
    COUNT(B.Booking_ID) AS BookingCount
FROM BOOKING AS B
JOIN Flight AS F ON B.FLIGHT_ID = F.FLIGHT_ID
GROUP BY F.DEPART_AIRPORT
ORDER BY BookingCount DESC;*/



























